begin_date = '2008-01-01'
end_date =  '2009-12-31'
weights = [0.25, 0.25, 0.25, 0.25]
rolling_window_of_portfolio_returns = 30

[input]
input_folder = 'input'
input_file = 'crisis_portfolio.csv'
delimiter = ','
index_col = 'Date'
parse_dates = ['Date']

[view]
asset_prices_ylabel = "Closing Prices, USD"
portfolio_returns_ylabel = "Daily Return, %"
portfolio_volatility_ylabel = "Daily Return, %"