version: 1
disable_existing_loggers: True
open_logging_file: true

formatters:
    console_format:
        format: '%(name)s | %(module)s | %(funcName)s | %(levelname)s | %(message)s'
    file_format:
        format: '%(asctime)s|%(module)s|%(funcName)s|%(levelname)s|%(message)s'

handlers:
    console:
        class: logging.StreamHandler
        level: WARNING
        formatter: console_format
        stream: ext://sys.stdout

    file:
        class: logging.FileHandler
        level: DEBUG
        formatter: file_format
        filename: C:\python_log\quantitative_risk.log
        mode: w

loggers:
    development_sorbonne:
        level: DEBUG
        handlers: [console, file]
        propagate: no
    production_sorbonne:
        level: INFO
        handlers: [file]
        propagate: no

root:
    level: DEBUG
    handlers: [console]
